version = 1

; Levels of context
; 1 = 32768
; 2 = 65536
; 3 = 98304
; 4 = 131072
; 5 = 163840
; 6 = 196608
; 7 = 229376

[Nex-Mini-2-35B-A3B-Reasoning]
m = /models/nex/n2/mini/libertaidai/Nex-N2-mini-IQ4_XS.gguf
mmproj = /models/nex/n2/mini/libertaidai/mmproj-Nex-N2-mini-F16.gguf
ctx-size = 196608
temp = 0.7
top-p = 0.95
top-k = 40
min-p = 0.0
n = 32768
batch-size = 2048
ubatch-size = 512
jinja = enabled
ngl = 99
flash-attn = auto
cache-type-k = q4_0
cache-type-v = q4_0

[Qwen-Max]
m = /models/mtp/qwen/3.6/27/Qwen3.6-27B-Q4_K_M.gguf
mmproj = /models/mtp/qwen/3.6/27/mmproj-BF16.gguf
ctx-size = 163840
temp = 0.7
top-p = 0.95
top-k = 20
min-p = 0.0
n = 32768
batch-size = 2048
ubatch-size = 512
n-predict = 8192
jinja = enabled
ngl = 99
flash-attn = on
cache-type-k = q4_0
cache-type-v = q4_0
chat-template-kwargs = {"enable_thinking": true}
spec-type = draft-mtp,ngram-mod
spec-draft-n-max = 2
spec-draft-p-min = 0.5
spec-ngram-mod-n-match = 24
spec-ngram-mod-n-min = 48
spec-ngram-mod-n-max = 64
no-mmap = true
parallel = 1

[Gemma-4-12B-Reasoning]
m = /models/abliterated/gemma/4/12/qat/Huihui-gemma-4-12B-it-qat-q4_0-unquantized-abliterated-Q4_K.gguf
mmproj = /models/abliterated/gemma/4/12/qat/mmproj-model-bf16.gguf
md = /models/abliterated/gemma/4/12/qat/mtp-ggml-model-bf16.gguf
ctx-size = 262144
batch-size = 2048
ubatch-size = 512
temp = 1.0
top-p = 0.95
top-k = 64
jinja = enabled
chat-template-file = /models/abliterated/gemma/4/12/qat/custom_pub_chat_template_gemma4.jinja
ngl = 999
ngld = 999
flash-attn = auto
cache-type-k = q4_0
cache-type-v = q4_0
fit = off
spec-type = draft-mtp
spec-draft-n-max = 3
spec-draft-type-k = q4_0
spec-draft-type-v = q4_0

;[Gemma-4-31B-Reasoning]
;[Qwen-Plus]
;[Gemma-Plus]
;[Nemotron-3-Nano-Omni-30B-Reasoning]
;[Ministral-14B-Instruct]
;[Devstral-Small-2-24B-Instruct]
;[Gemma-Pro]
;[Nemotron-Cascade-2-30B-A3B]
;[Qwopus-Plus]
;[Qwopus-Max]
;[Qwable-35B-A3B-Reasoning]
